version: "3.8"

services:

  minecraftserver:
    image: itzg/minecraft-server
    container_name: minecraftserver
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - minecraftserver:/data

volumes:
  minecraftserver: {}
