version: "2.1"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    restart: unless-stopped
    network_mode: host
    ports:
      - "25565:25565"
    environment:
      - PUID=0 #change if not root user
      - PGID=0 #change if not root user
      - TZ=America/New_York
      - VERSION=docker
    volumes:
      - plexdata:/config
      - /media/downloads/tvseries:/tv
      - /media/downloads/movies:/movies

volumes:
  plexdata: {}
