version: "2.1"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001 #change for your user. run command id (pi is 1000, root is 0)
      - PGID=1001 #change for your user. run command id (pi is 1000, root is 0)
      - TZ=America/New_York
      - VERSION=latest
    # - PLEX_CLAIM=  go to plex.tv/claim
    volumes:
      - data:/config
      - /downloads/tvseries:/tv
      - /downloads/movies:/movies

volumes:
  data: {}
