version: '3.8'

services:
  sonarqube:
    container_name: sonarqubepi
    image: iamjavadali/sonarqubepi
    ports:
      - "9000:9000"
    restart: always
#   environment:
#     - SONARQUBE_JDBC_USERNAME=sonar
#     - SONARQUBE_JDBC_PASSWORD=sonar
#     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
