version: '3.1'

services:

  nginxproxymanagerpi:
    build:
      context: ./nginxproxymanager
    image: moneydontbuyclass/nginxproxymanagerpi
    container_name: nginxproxymanagerpi
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 
      - 81:81 #You can change port 81 to any avaiable port on your network.    
    volumes:
      - /dockerdata/nginx-proxy-manager/data:/var/www/html
      - /dockerdata/nginx-proxy-manager/data/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginxproxymanagerpidb
      - nginxproxymanagerpistats

  nginxproxymanagerpidb:
    build:
      context: ./mariadb
    image: moneydontbuyclass/nginxproxymanagerpidb
    container_name: nginxproxymanagerpidb
    restart: unless-stopped
    volumes:
      - /dockerdata/nginx-proxy-manager/mariadb:/var/lib/mysql

  nginxproxymanagerpistats:
    build:
      context: ./goaccess
    image: moneydontbuyclass/nginxproxymanagerpistats
    container_name: nginxproxymanagerpistats
    restart: unless-stopped
    ports:
      - 7880:7880   
    volumes:
      - /dockerdata/nginx-proxy-manager/data/logs:/opt/log:ro

volumes:
  nginxproxymanagerpi: {}