version: "2.1"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001 #change for your user. run command id (pi is 1000, root is 0)
      - PGID=1001 #change for your user. run command id (pi is 1000, root is 0)
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=claim-BjNFxenhHeLrxsSsuwEK  #go to plex.tv/claim
    volumes:
      - data:/config
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/tvseries:/tv
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/movies:/movies
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/music:/music
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/photos:/photos
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/downloads:/downloads

volumes:
  data: {}

# run the following command if 32400 port did not work. sudo iptables -I INPUT -j ACCEPT