version: '3.1'

services:

  wordpress:
    build:
      context: ./wordpress
    image: moneydontbuyclass/wordpresspi
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 1080:80 #You can change port 1080 to any avaiable port on your network.   
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpressdb
      - wordpressredis

  wordpressdb:
    build:
      context: ./mysql
    image: moneydontbuyclass/wordpresspidb
    container_name: wordpressdb
    restart: always
    volumes:
      - wordpressdb:/var/lib/mysql

  wordpressredis:
    image: "redis:alpine"
    container_name: wordpressredis
    restart: always

volumes:
  wordpress: {}
  wordpressdb: {}
