version: "2.1"

services:
  
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: Transmission
    environment:
      - PUID=1000 #change this to your docker user ID - default: pi=1000. root = 0
      - PGID=1000 #change this to your docker user ID - default: pi=1000. root = 0
      - TZ=America/New_York #change this to your local time zone
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - transmission:/config
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/downloads:/downloads
      - /var/lib/docker/volumes/filebrowser_filebrowser/_data/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  transmission: {}